name: TestFlight prerelease

on:
  workflow_dispatch:
    inputs:
      changelog:
        type: string
        required: true
        description: What internal testers should test

jobs:
  build_ios:
    name: Build iOS prerelease
    type: build
    params:
      platform: ios
      profile: production
      message: ${{ inputs.changelog }}

  testflight:
    name: Deliver to internal TestFlight
    needs: [build_ios]
    type: testflight
    params:
      build_id: ${{ needs.build_ios.outputs.build_id }}
      profile: production
      changelog: ${{ inputs.changelog }}
      submit_beta_review: false
      wait_processing_timeout_seconds: 3600
