// Generated by agent/skills/app-chat/cli/tests/test_chat_events_fixture.py (REGEN_EVENT_FIXTURES=1); do not edit.
export const appChatFixtures = {
  "echo": {
    "id": 1,
    "input_method": "typed",
    "intent_id": "intent-1",
    "text": "here is the photo",
    "ts": "2026-01-01T00:00:00+00:00",
    "type": "user"
  },
  "history": {
    "cursor": null,
    "events": [
      {
        "id": 1,
        "input_method": "typed",
        "intent_id": "intent-1",
        "text": "here is the photo",
        "ts": "2026-01-01T00:00:00+00:00",
        "type": "user"
      },
      {
        "attachments": [
          {
            "height": 480,
            "id": "att-photo",
            "mime": "image/jpeg",
            "name": "photo.jpg",
            "size": 12345,
            "width": 640
          }
        ],
        "id": 2,
        "text": "nice shot",
        "ts": "2026-01-01T00:00:00+00:00",
        "type": "chat"
      }
    ]
  }
} as const;
