// AUTO-GENERATED by vestad's API contract test. Do not edit by hand.
// Regenerate: cd vestad && REGEN_API_FIXTURES=1 cargo test -p vestad api_contract
// Checked by apps/core/src/protocol/sync-contract.test.ts against @vesta/core's frame types.
export const syncProtocolFixtures = {
  "deltas": {
    "agent": {
      "info": {
        "activityState": "thinking",
        "booting": false,
        "buildPhase": null,
        "operation": "backing_up",
        "rateLimited": {
          "resetsAt": 1787986800,
          "window": "seven_day"
        },
        "services": {
          "dashboard": {
            "port": 8080,
            "public": false,
            "rev": 3
          }
        },
        "startedAt": "2026-01-01T00:00:00Z",
        "status": "alive"
      },
      "name": "sample-agent",
      "type": "agent"
    },
    "agent_notifications": {
      "agent": "sample-agent",
      "pending": [
        {
          "id": 7,
          "notif_id": "whatsapp-123",
          "source": "whatsapp",
          "summary": "new message",
          "type": "notification"
        }
      ],
      "type": "agent_notifications"
    },
    "agent_removed": {
      "name": "stopped-agent",
      "type": "agent_removed"
    },
    "devices": {
      "devices": [
        {
          "descriptor": "Vesta Desktop on macOS",
          "id": "device-1",
          "kind": "desktop",
          "lastSeen": "2026-01-01T00:00:00Z",
          "position": {
            "accuracyM": 50.0,
            "latitude": 51.5074,
            "longitude": -0.1278,
            "place": {
              "city": "London",
              "country": "United Kingdom",
              "region": "England"
            }
          },
          "positionAt": "2026-01-01T00:00:00Z",
          "present": true,
          "pushEnabled": false,
          "timezone": "Europe/London"
        }
      ],
      "type": "devices"
    },
    "presence": {
      "any_focused": true,
      "type": "presence"
    },
    "rooms": {
      "rooms": [
        {
          "agents": [
            "sample"
          ],
          "createdAt": 1756900000,
          "id": "dm:sample",
          "lastMessageAt": 1756903000,
          "name": null
        },
        {
          "agents": [
            "sample",
            "scout"
          ],
          "createdAt": 1756900100,
          "id": "grp-0011223344556677",
          "lastMessageAt": null,
          "name": "trip planning"
        }
      ],
      "type": "rooms"
    },
    "state": {
      "scope": "gateway",
      "type": "state",
      "value": {
        "autoUpdate": true,
        "channel": "stable",
        "lan": {
          "exposed": false,
          "url": null
        },
        "lastUserNotificationAt": 1700000400,
        "latestVersion": "0.1.1",
        "managed": false,
        "operation": {
          "agent": "sample-agent",
          "done": 1,
          "error": null,
          "kind": "update",
          "phase": "snapshotting",
          "targetVersion": "0.1.1",
          "total": 2,
          "warnings": [
            "other-agent: backup failed (disk full)"
          ]
        },
        "port": 4111,
        "tunnelUrl": "https://sample.vesta.run",
        "updateAvailable": true,
        "userNotificationsSeenAt": 1700000000,
        "version": "0.1.0"
      }
    },
    "user_notification": {
      "agent": "sample-agent",
      "at": 1700000400,
      "body": "hello",
      "id": 3,
      "kind": "message",
      "title": "sample-agent",
      "type": "user_notification"
    }
  },
  "hello": {
    "min_supported": "0.2.16",
    "type": "hello",
    "version": "0.1.0"
  },
  "snapshot": {
    "tree": {
      "agents": {
        "sample-agent": {
          "info": {
            "activityState": "thinking",
            "booting": false,
            "buildPhase": null,
            "operation": "backing_up",
            "rateLimited": {
              "resetsAt": 1787986800,
              "window": "seven_day"
            },
            "services": {
              "dashboard": {
                "port": 8080,
                "public": false,
                "rev": 3
              }
            },
            "startedAt": "2026-01-01T00:00:00Z",
            "status": "alive"
          },
          "notifications": {
            "pending": [
              {
                "id": 7,
                "notif_id": "whatsapp-123",
                "source": "whatsapp",
                "summary": "new message",
                "type": "notification"
              }
            ]
          }
        }
      },
      "devices": [
        {
          "descriptor": "Vesta Desktop on macOS",
          "id": "device-1",
          "kind": "desktop",
          "lastSeen": "2026-01-01T00:00:00Z",
          "position": {
            "accuracyM": 50.0,
            "latitude": 51.5074,
            "longitude": -0.1278,
            "place": {
              "city": "London",
              "country": "United Kingdom",
              "region": "England"
            }
          },
          "positionAt": "2026-01-01T00:00:00Z",
          "present": true,
          "pushEnabled": false,
          "timezone": "Europe/London"
        }
      ],
      "gateway": {
        "autoUpdate": true,
        "channel": "stable",
        "lan": {
          "exposed": false,
          "url": null
        },
        "lastUserNotificationAt": 1700000400,
        "latestVersion": "0.1.1",
        "managed": false,
        "operation": {
          "agent": "sample-agent",
          "done": 1,
          "error": null,
          "kind": "update",
          "phase": "snapshotting",
          "targetVersion": "0.1.1",
          "total": 2,
          "warnings": [
            "other-agent: backup failed (disk full)"
          ]
        },
        "port": 4111,
        "tunnelUrl": "https://sample.vesta.run",
        "updateAvailable": true,
        "userNotificationsSeenAt": 1700000000,
        "version": "0.1.0"
      },
      "rooms": [
        {
          "agents": [
            "sample"
          ],
          "createdAt": 1756900000,
          "id": "dm:sample",
          "lastMessageAt": 1756903000,
          "name": null
        },
        {
          "agents": [
            "sample",
            "scout"
          ],
          "createdAt": 1756900100,
          "id": "grp-0011223344556677",
          "lastMessageAt": null,
          "name": "trip planning"
        }
      ]
    },
    "type": "snapshot"
  }
} as const;
