// AUTO-GENERATED by vestad's API contract test. Do not edit by hand.
// Regenerate: cd vestad && REGEN_API_FIXTURES=1 cargo test -p vestad api_contract
// Checked by apps/core/src/api/api-contract.test.ts against @vesta/core's TypeScript types.
export const vestadApiFixtures = {
  "agent_backup_settings": {
    "enabled": true,
    "has_override": false,
    "retention": {
      "periodic": 1,
      "pre_update_versions": 5
    }
  },
  "agent_status_json": {
    "booting": false,
    "id": "c0ffee",
    "name": "sample-agent",
    "status": "alive",
    "ws_port": 4200
  },
  "agent_statuses": [
    "alive",
    "setting_up",
    "starting",
    "not_authenticated",
    "unprovisioned",
    "rebuilding",
    "stopped",
    "dead",
    "not_found"
  ],
  "agents": [
    {
      "booting": false,
      "name": "sample-agent",
      "startedAt": "2026-01-01T00:00:00Z",
      "status": "alive",
      "ws_port": 4200
    },
    {
      "booting": false,
      "name": "stopped-agent",
      "status": "stopped",
      "ws_port": 4201
    }
  ],
  "backups": [
    {
      "agent_name": "sample-agent",
      "backup_type": "manual",
      "created_at": "20260101-000000",
      "id": "1a2b3c4d",
      "size": 1234567890
    },
    {
      "agent_name": "sample-agent",
      "backup_type": "periodic",
      "created_at": "20260101-000000",
      "id": "1a2b3c4d",
      "size": 1234567890,
      "vestad_version": "0.1.0"
    },
    {
      "agent_name": "sample-agent",
      "backup_type": "pre_update",
      "created_at": "20260101-000000",
      "from_version": "v0.1.0",
      "id": "1a2b3c4d",
      "size": 1234567890,
      "vestad_version": "0.1.0"
    },
    {
      "agent_name": "sample-agent",
      "backup_type": "pre_restore",
      "created_at": "20260101-000000",
      "id": "1a2b3c4d",
      "size": 1234567890,
      "vestad_version": "0.1.0"
    }
  ],
  "file_read": {
    "content": "hello",
    "encoding": "utf-8",
    "is_dir": false,
    "mode": 420,
    "path": "notes/todo.md",
    "readonly": false,
    "size": 5
  },
  "gateway_info": {
    "lan": {
      "exposed": true,
      "url": "https://192.168.1.20:4111"
    },
    "port": 4111,
    "tunnel_url": "https://sample.vesta.run"
  },
  "gateway_settings": {
    "auto_backup": {
      "enabled": true,
      "every_n_days": 1,
      "retention": {
        "periodic": 1,
        "pre_update_versions": 5
      }
    },
    "auto_update": true,
    "channel": "stable",
    "push_notifications": {
      "agent_status": true,
      "device_connected": true,
      "gateway_updated": true,
      "message": true,
      "needs_user": true,
      "task": false,
      "update_available": false
    }
  },
  "host_folders": {
    "folders": [
      "/home/sample/Documents"
    ]
  },
  "mounts": {
    "mounts": [
      {
        "container_path": "/mnt/notes",
        "host_path": "/home/sample/notes",
        "writable": false
      }
    ]
  },
  "mounts_updated": {
    "mounts": [
      {
        "container_path": "/mnt/notes",
        "host_path": "/home/sample/notes",
        "writable": false
      }
    ],
    "restart_required": true
  },
  "renamed": {
    "name": "sample-agent-2"
  },
  "start_all": {
    "results": [
      {
        "name": "sample-agent",
        "ok": true
      },
      {
        "error": "failed to start",
        "name": "broken-agent",
        "ok": false
      }
    ]
  },
  "tree_entry": {
    "is_dir": false,
    "mode": 420,
    "path": "notes/todo.md"
  },
  "version": {
    "api_compat": "0.2",
    "auto_update": true,
    "channel": "stable",
    "dev_mode": false,
    "latest_version": "0.1.1",
    "update_available": true,
    "version": "0.1.0"
  }
} as const;
