"""App-chat event fixture emitter: run one user message through the real intake (POST /message, the
live echo, the store) plus one agent reply through the store, and commit the exact wire shapes as a
TypeScript fixture, so @vesta/core's chat parser is proven against what the service really emits.
Regenerate with REGEN_EVENT_FIXTURES=1.

The fixture's contract is the app-chat -> client seam: the live chat socket frame (the echo of a send,
carrying its intent_id) and the paged history (GET /history, {events, cursor}). Both are the same
StoredEvent shape, so the fixture carries one page holding the echoed user row and a reply with
attachments, plus the echo frame as the socket delivered it.
"""

import asyncio
import json
import os
import pathlib as pl

from aiohttp.test_utils import TestClient, TestServer
from app_chat_cli.service import ServiceState, create_app
from app_chat_cli.store import Store, StoredEvent, store_path

# ts is a wall-clock value stamped inside intake; normalize it so the committed fixture is stable. The
# ids are the contract under test and are kept exactly as the real store produced them.
_FIXED_TS = "2026-01-01T00:00:00+00:00"


def _fixture_path() -> pl.Path:
    return pl.Path(__file__).resolve().parents[5] / "apps" / "core" / "fixtures" / "app-chat-events.ts"


async def _intake(state: ServiceState) -> StoredEvent:
    """POST one message with a client intent_id and return the frame the live socket echoed."""
    queue: asyncio.Queue[StoredEvent] = asyncio.Queue()
    state.subscribers.add(queue)
    server = TestServer(create_app(state))
    client = TestClient(server)
    await client.start_server()
    try:
        response = await client.post(
            "/message",
            json={"text": "here is the photo", "input_method": "typed", "intent_id": "intent-1"},
        )
        assert response.status == 200
    finally:
        await client.close()
    return queue.get_nowait()


def _reply() -> StoredEvent:
    """The agent's reply as `app-chat send --attach` appends it: metadata only, ids the store serves."""
    return {
        "type": "chat",
        "ts": _FIXED_TS,
        "text": "nice shot",
        "attachments": [
            {
                "id": "att-photo",
                "name": "photo.jpg",
                "mime": "image/jpeg",
                "size": 12345,
                "width": 640,
                "height": 480,
            }
        ],
    }


def _fixture_content(tmp_path: pl.Path) -> str:
    store = Store(store_path(tmp_path / "data"))
    state = ServiceState(store, tmp_path / "notifications", tmp_path / "attachments")
    echo = asyncio.run(_intake(state))
    echo["ts"] = _FIXED_TS
    store.append(_reply())
    events, cursor = store.page()
    for event in events:
        event["ts"] = _FIXED_TS
    payload = {"echo": echo, "history": {"events": events, "cursor": cursor}}
    body = json.dumps(payload, indent=2, sort_keys=True)
    return (
        "// Generated by agent/skills/app-chat/cli/tests/test_chat_events_fixture.py"
        " (REGEN_EVENT_FIXTURES=1); do not edit.\n"
        f"export const appChatFixtures = {body} as const;\n"
    )


def test_chat_events_fixture_up_to_date(tmp_path: pl.Path) -> None:
    """Run the real intake and store paths and fail if the committed fixture is stale."""
    path = _fixture_path()
    content = _fixture_content(tmp_path)
    if "REGEN_EVENT_FIXTURES" in os.environ:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
        return
    committed = path.read_text() if path.exists() else ""
    assert committed == content, (
        "\n\nApp-chat event fixture is stale.\nRegenerate with:\n"
        "  uv run --project agent/skills/app-chat/cli pytest agent/skills/app-chat/cli/tests/test_chat_events_fixture.py"
        " (with REGEN_EVENT_FIXTURES=1)\n"
        f"then commit {path}\n"
    )


def test_echo_carries_the_intent_id_and_store_id(tmp_path: pl.Path) -> None:
    """The echo is what confirms a client's optimistic bubble: it must carry the client's intent_id and the
    store-assigned id the history page will serve for the same row."""
    store = Store(store_path(tmp_path / "data"))
    state = ServiceState(store, tmp_path / "notifications", tmp_path / "attachments")
    echo = asyncio.run(_intake(state))
    events, _ = store.page()
    assert echo["intent_id"] == "intent-1"
    assert echo["id"] == events[0]["id"] == 1
