import { describe, expect, it } from "vitest";

import { vestadApiFixtures } from "../../fixtures/vestad-api-fixtures";
import { parseChatEvent, parseHistoryPage } from "./parse-chat";

// The page the chat node serves at `/rooms/{id}/history`, generated by vestad's own API contract
// test. Its events are the rows the room socket echoes live, so parsing them with the boundary
// parser proves the node to client seam at runtime, while `api-contract.test.ts` proves the same
// page at compile time: a renamed field on either side fails `npm run check`.
const page = (): unknown =>
  JSON.parse(JSON.stringify(vestadApiFixtures.chat_history));

describe("chat event contract (the node's history page)", () => {
  it("parses the echo of a send, carrying the client's intent id and the store id", () => {
    const parsed = parseChatEvent(
      JSON.parse(JSON.stringify(vestadApiFixtures.chat_history.events[0])),
    );
    expect(parsed).toEqual({
      type: "user",
      id: 1,
      ts: "2026-09-04T09:00:00Z",
      room: "dm:sample-agent",
      sender: "user",
      text: "are we still on for friday?",
      input_method: "typed",
      intent_id: "c-sample-1",
    });
  });

  it("parses every event on the page, attachments included", () => {
    const parsed = parseHistoryPage(page());
    expect(parsed.cursor).toBe(1);
    expect(parsed.events.map((event) => event.type)).toEqual(["user", "chat"]);
    const reply = parsed.events[1];
    expect(reply?.type === "chat" ? reply.sender : null).toBe("sample-agent");
    expect(reply?.type === "chat" ? reply.attachments : null).toEqual([
      {
        id: "0f1e2d3c4b5a69788796a5b4c3d2e1f0",
        name: "photo.png",
        mime: "image/png",
        size: 1234,
        width: 640,
        height: 480,
      },
    ]);
  });

  it("drops an event the parser cannot classify instead of rendering it", () => {
    expect(parseChatEvent({ type: "chat", id: 3 })).toBeNull();
    expect(parseChatEvent({ type: "mystery", id: 3, text: "x" })).toBeNull();
    expect(
      parseHistoryPage({ events: [{ type: "user", id: "1", text: "x" }] })
        .events,
    ).toEqual([]);
  });
});
