"""Event type contract tests: pin the agent->web stream contract with fixtures + `satisfies`.

The single source of truth is the StreamEvent/HistoryEvent TypedDicts in core.events. This module
generates apps/web/src/lib/stream-event-fixtures.ts from a representative instance of every event type,
and the web's api-contract.test.ts `satisfies`-checks those fixtures against its VestaEvent union. A
field-name or field-type mismatch on either side then fails CI (mirrors vestad's REGEN_API_FIXTURES flow).
"""

import json
import os
import typing as tp
from pathlib import Path

from core.events import (
    AssistantEvent,
    ChatEvent,
    ErrorEvent,
    EventBus,
    HistoryEvent,
    NotificationEvent,
    StatusEvent,
    SubagentStartEvent,
    SubagentStopEvent,
    ThinkingEvent,
    ToolEndEvent,
    ToolStartEvent,
    UserEvent,
)

# One representative instance of every StreamEvent variant, then HistoryEvent (which nests them).
# Every required field is populated with a value of the correct type so the web's `satisfies` check
# catches both field-name and field-type drift.
_STREAM_FIXTURES: list[tp.Any] = [
    StatusEvent(type="status", ts="2026-01-01T00:00:00Z", state="thinking"),
    UserEvent(type="user", ts="2026-01-01T00:00:00Z", text="hello", input_method="typed"),
    AssistantEvent(type="assistant", ts="2026-01-01T00:00:00Z", text="hi"),
    ThinkingEvent(type="thinking", ts="2026-01-01T00:00:00Z", text="hmm", signature="sig"),
    ChatEvent(type="chat", ts="2026-01-01T00:00:00Z", text="yo"),
    ToolStartEvent(type="tool_start", ts="2026-01-01T00:00:00Z", tool="Bash", input="ls", subagent=False),
    ToolEndEvent(type="tool_end", ts="2026-01-01T00:00:00Z", tool="Bash", subagent=False),
    ErrorEvent(type="error", ts="2026-01-01T00:00:00Z", text="oops"),
    NotificationEvent(type="notification", ts="2026-01-01T00:00:00Z", source="email", summary="new mail"),
    SubagentStartEvent(type="subagent_start", ts="2026-01-01T00:00:00Z", agent_id="abc", agent_type="browser"),
    SubagentStopEvent(type="subagent_stop", ts="2026-01-01T00:00:00Z", agent_id="abc", agent_type="browser"),
]

# HistoryEvent has no `ts` field (it is the snapshot wrapper, not a streamed event), so none is set here.
_HISTORY_FIXTURE: HistoryEvent = HistoryEvent(
    type="history",
    events=[
        StatusEvent(type="status", ts="2026-01-01T00:00:00Z", state="idle"),
        AssistantEvent(type="assistant", ts="2026-01-01T00:00:00Z", text="hi"),
    ],
    state="idle",
    cursor=42,
)

_FIXTURES_HEADER = (
    "// AUTO-GENERATED by the agent's stream contract test. Do not edit by hand.\n"
    "// Regenerate: cd agent && REGEN_STREAM_FIXTURES=1 uv run pytest tests/test_contract.py\n"
    "// Checked by apps/web/src/lib/api-contract.test.ts against the web's VestaEvent type.\n"
)


def _fixtures_content() -> str:
    payload = {"stream_events": _STREAM_FIXTURES, "history_event": _HISTORY_FIXTURE}
    return f"{_FIXTURES_HEADER}export const streamEventFixtures = {json.dumps(payload, indent=2)} as const;\n"


def _fixtures_path() -> Path:
    return Path(__file__).resolve().parents[2] / "apps" / "web" / "src" / "lib" / "stream-event-fixtures.ts"


def test_stream_event_fixtures_up_to_date():
    """Generate the TS fixtures the web `satisfies`-checks, and fail if the committed copy is stale."""
    path = _fixtures_path()
    if not path.parent.exists():
        # Agent-only checkout (e.g. inside the container): nothing to check.
        return

    content = _fixtures_content()
    if "REGEN_STREAM_FIXTURES" in os.environ:
        path.write_text(content)
        return

    committed = path.read_text() if path.exists() else ""
    assert committed == content, (
        f"\n\nStream event fixtures are stale.\nRegenerate with:\n"
        f"  cd agent && REGEN_STREAM_FIXTURES=1 uv run pytest tests/test_contract.py\n"
        f"then commit {path}\n"
    )


def test_all_stream_events_serializable():
    """Every event fixture round-trips through json without loss of its type tag."""
    for event in [*_STREAM_FIXTURES, _HISTORY_FIXTURE]:
        serialized = json.dumps(event)
        assert isinstance(serialized, str)
        roundtrip = json.loads(serialized)
        assert roundtrip["type"] == event["type"]


def test_eventbus_roundtrip_all_types(tmp_path):
    """Emit each persistable event type, read back, verify the type tag survives."""
    bus = EventBus(data_dir=tmp_path)

    # `status` is transient and intentionally not persisted (see EventBus.emit).
    persistable = [event for event in _STREAM_FIXTURES if event["type"] != "status"]
    for event in persistable:
        bus.emit(event)

    stored, _ = bus.recent(limit=len(persistable) + 1)
    stored_types = {stored_event["type"] for stored_event in stored}

    for event in persistable:
        assert event["type"] in stored_types, f"{event['type']} not found in stored events"

    bus.close()
