// Every gateway route lives once in @vesta/core as a function taking the app's HttpClient first;
// mobile's ApiClient is one structurally, so call sites pass it unchanged. These names keep
// mobile's import path stable. LEGACY(remove-when: the chat-session epic points call sites at
// @vesta/core directly): delete this module then.
export {
  completeClaudeOAuth,
  completeOpenAIOAuth,
  createBackup,
  deleteAgent,
  deleteBackup,
  fetchAgentBackupSettings as getAgentBackupSettings,
  fetchAgentClaudeModels as fetchClaudeModels,
  fetchFileTree,
  fetchGatewayInfo,
  fetchGatewaySettings,
  fetchOpenRouterModels,
  fetchUsage,
  fetchVoiceStatus,
  getAgentMounts,
  getHostFolderSuggestions,
  getNotificationHistory,
  getNotificationInterruptRules as getNotificationRules,
  getProvider,
  listBackups,
  prepareSpeech,
  provisionAgent,
  readFile,
  registerMobileDevice,
  renameAgent,
  restartAgent,
  restoreBackup,
  setAgentBackupSettings,
  setAgentMounts,
  setContextWindow,
  setModel,
  setNotificationInterruptRules as setNotificationRules,
  setVoiceEnabled,
  setVoiceSetting,
  signOutProvider,
  startAgent,
  startClaudeOAuth,
  startOpenAIOAuth,
  stopAgent,
  unregisterMobileDevice,
  updateGatewaySettings,
  validateOpenRouterKey,
  writeFile,
} from "@vesta/core";
export type {
  OpenRouterModelOption,
  ProviderResource,
  ProviderSelection,
} from "@vesta/core";
