#!/usr/bin/env python3
"""Generate web and React Native tokens from design/tokens.json."""

from __future__ import annotations

import argparse
import json
import math
import pathlib
import re
import sys
from typing import Any

ROOT = pathlib.Path(__file__).resolve().parent.parent
SOURCE = ROOT / "design" / "tokens.json"
WEB_OUTPUT = ROOT / "apps" / "web" / "src" / "design-tokens.css"
WEB_TYPESCRIPT_OUTPUT = ROOT / "apps" / "web" / "src" / "design-tokens.ts"
MOBILE_OUTPUT = ROOT / "apps" / "mobile" / "src" / "theme" / "generated.ts"
MOBILE_CONFIG_OUTPUT = ROOT / "apps" / "mobile" / "src" / "theme" / "native-config.generated.json"

OKLCH_PATTERN = re.compile(
    r"^oklch\((?P<lightness>[0-9.]+)\s+(?P<chroma>[0-9.]+)\s+"
    r"(?P<hue>[0-9.]+)(?:\s*/\s*(?P<alpha>[0-9.]+)%?)?\)$"
)


def _css_variables(values: dict[str, str], indent: str = "  ") -> str:
    return "\n".join(f"{indent}--{name}: {value};" for name, value in values.items())


def _css(tokens: dict[str, Any]) -> str:
    colors = tokens["colors"]
    radii = tokens["radii"]
    spacing = tokens["spacing"]
    families = tokens["typography"]["families"]
    sizes = tokens["typography"]["sizes"]
    theme_color_names = list(colors["light"])
    root_extra = {
        "launch-background": tokens["launch"]["background"],
        "radius": radii["base-css"],
        "rounded-squircle-lg": radii["squircle-lg-css"],
        "rounded-squircle-md": radii["squircle-md-css"],
        "rounded-squircle-sm": radii["squircle-sm-css"],
        "page-padding-x": spacing["page-css"],
        "frame-inset": spacing["frame-inset-css"],
    }
    theme_colors = "\n".join(f"  --color-{name}: var(--{name});" for name in reversed(theme_color_names))
    theme_sizes = "\n".join(f"  --text-{name}: {format(size / 16, '.6g')}rem;" for name, size in sizes.items())
    return f"""/* Generated by scripts/sync-design-tokens.py. Do not edit directly. */
:root {{
{_css_variables(colors["light"])}
{_css_variables(root_extra)}
}}

@supports not (corner-shape: squircle) {{
  :root {{
    --rounded-squircle-lg: calc(var(--radius) * 3);
    --rounded-squircle-md: calc(var(--radius) * 2.6);
    --rounded-squircle-sm: calc(var(--radius) * 1.6);
  }}
}}

.vibrancy {{
{_css_variables(colors["vibrancy-light"])}
}}

.vibrancy.dark {{
{_css_variables(colors["vibrancy-dark"])}
}}

.dark {{
{_css_variables(colors["dark"])}
}}

@theme inline {{
  --font-sans: {families["sans"]["css"]};
  --font-heading: {families["heading"]["css"]};
  --font-serif: {families["heading"]["css"]};
  --font-mono:
    "JetBrains Mono Variable", ui-monospace, SFMono-Regular, Menlo, Consolas,
    "Liberation Mono", monospace;
{theme_sizes}
{theme_colors}
  --radius-sm: calc(var(--radius) * 0.6);
  --radius-md: calc(var(--radius) * 0.8);
  --radius-lg: var(--radius);
  --radius-xl: calc(var(--radius) * 1.4);
  --radius-2xl: calc(var(--radius) * 1.8);
  --radius-3xl: calc(var(--radius) * 2.2);
  --radius-4xl: calc(var(--radius) * 2.6);
  --radius-squircle-lg: var(--rounded-squircle-lg);
  --radius-squircle-md: var(--rounded-squircle-md);
  --radius-squircle-sm: var(--rounded-squircle-sm);
  --shadow-sm: 0 1px 3px 0 rgb(0 0 0 / 0.06), 0 1px 2px -1px rgb(0 0 0 / 0.06);
}}
"""


def _linear_to_srgb(value: float) -> float:
    if value <= 0.0031308:
        return 12.92 * value
    return 1.055 * (value ** (1 / 2.4)) - 0.055


def _native_color(value: str) -> str:
    match = OKLCH_PATTERN.match(value)
    if match is None:
        raise ValueError(f"unsupported color token: {value}")
    lightness = float(match.group("lightness"))
    chroma = float(match.group("chroma"))
    hue = math.radians(float(match.group("hue")))
    alpha_text = match.group("alpha")
    alpha = 1.0 if alpha_text is None else float(alpha_text)
    if alpha_text is not None and "%" in value:
        alpha /= 100

    a = chroma * math.cos(hue)
    b = chroma * math.sin(hue)
    light = lightness + 0.3963377774 * a + 0.2158037573 * b
    medium = lightness - 0.1055613458 * a - 0.0638541728 * b
    short = lightness - 0.0894841775 * a - 1.2914855480 * b
    light, medium, short = light**3, medium**3, short**3
    red = 4.0767416621 * light - 3.3077115913 * medium + 0.2309699292 * short
    green = -1.2684380046 * light + 2.6097574011 * medium - 0.3413193965 * short
    blue = -0.0041960863 * light - 0.7034186147 * medium + 1.707614701 * short
    channels = [round(max(0, min(1, _linear_to_srgb(channel))) * 255) for channel in (red, green, blue)]
    if alpha < 1:
        return f"rgba({channels[0]}, {channels[1]}, {channels[2]}, {alpha:.2f})"
    return "#" + "".join(f"{channel:02x}" for channel in channels)


def _typescript(tokens: dict[str, Any]) -> str:
    colors = tokens["colors"]
    native_colors = {theme: {name: _native_color(value) for name, value in colors[theme].items()} for theme in ("light", "dark")}
    payload = {
        "launch": {"background": _native_color(tokens["launch"]["background"])},
        "colors": native_colors,
        "typography": tokens["typography"],
        "radii": {
            "base": tokens["radii"]["base-native"],
            "card": tokens["radii"]["card-native"],
            "control": tokens["radii"]["control-native"],
            "button": tokens["radii"]["button-native"],
            "bubble": tokens["radii"]["bubble-native"],
            "pill": tokens["radii"]["pill-native"],
        },
        "spacing": {"page": tokens["spacing"]["page-native"]},
        "orb": tokens["orb"],
    }
    serialized = _typescript_value(payload)
    return f"// Generated by scripts/sync-design-tokens.py. Do not edit directly.\nexport const designTokens = {serialized} as const;\n"


def _native_config_json(tokens: dict[str, Any]) -> str:
    dark = tokens["colors"]["dark"]
    payload = {
        "background": _native_color(dark["background"]),
        "splashBackground": _native_color(tokens["launch"]["background"]),
        "primary": _native_color(dark["primary"]),
    }
    return json.dumps(payload, indent=2) + "\n"


def _web_typescript(tokens: dict[str, Any]) -> str:
    serialized = _typescript_value(tokens["orb"])
    return f"// Generated by scripts/sync-design-tokens.py. Do not edit directly.\nexport const orbColors = {serialized} as const;\n"


def _typescript_key(value: str) -> str:
    if re.fullmatch(r"[A-Za-z_$][A-Za-z0-9_$]*", value):
        return value
    return json.dumps(value, ensure_ascii=False)


def _typescript_string(value: str) -> str:
    if '"' in value and "'" not in value:
        return "'" + value + "'"
    return json.dumps(value, ensure_ascii=False)


def _typescript_value(value: Any, level: int = 0) -> str:
    if isinstance(value, dict):
        indent = "  " * level
        child_indent = "  " * (level + 1)
        rows = ["{"]
        for key, child in value.items():
            rows.append(f"{child_indent}{_typescript_key(str(key))}: {_typescript_value(child, level + 1)},")
        rows.append(f"{indent}}}")
        return "\n".join(rows)
    if isinstance(value, list):
        return "[" + ", ".join(_typescript_value(item, level) for item in value) + "]"
    if isinstance(value, str):
        return _typescript_string(value)
    if isinstance(value, bool):
        return "true" if value else "false"
    if value is None:
        return "null"
    return str(value)


def _sync(path: pathlib.Path, content: str, check: bool) -> bool:
    current = path.read_text() if path.exists() else ""
    if current == content:
        return True
    if check:
        print(f"out of date: {path.relative_to(ROOT)}", file=sys.stderr)
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    print(f"generated {path.relative_to(ROOT)}")
    return True


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    tokens = json.loads(SOURCE.read_text())
    results = [
        _sync(WEB_OUTPUT, _css(tokens), args.check),
        _sync(WEB_TYPESCRIPT_OUTPUT, _web_typescript(tokens), args.check),
        _sync(MOBILE_OUTPUT, _typescript(tokens), args.check),
        _sync(MOBILE_CONFIG_OUTPUT, _native_config_json(tokens), args.check),
    ]
    return 0 if all(results) else 1


if __name__ == "__main__":
    raise SystemExit(main())
