PLAYWRIGHT_TOOL_SUFFIXES = [
    "browser_click",
    "browser_close",
    "browser_console_messages",
    "browser_drag",
    "browser_evaluate",
    "browser_file_upload",
    "browser_fill_form",
    "browser_handle_dialog",
    "browser_hover",
    "browser_navigate",
    "browser_navigate_back",
    "browser_network_requests",
    "browser_press_key",
    "browser_resize",
    "browser_select_option",
    "browser_snapshot",
    "browser_take_screenshot",
    "browser_type",
    "browser_wait_for",
    "browser_tabs",
    "browser_install",
    "browser_mouse_click_xy",
    "browser_mouse_drag_xy",
    "browser_mouse_move_xy",
    "browser_pdf_save",
    "browser_start_tracing",
    "browser_stop_tracing",
]

PLAYWRIGHT_TOOL_IDS = [f"mcp__playwright__{suffix}" for suffix in PLAYWRIGHT_TOOL_SUFFIXES]
