import { describe, expect, it } from "vitest";

import { vestadApiFixtures } from "../../fixtures/vestad-api-fixtures";
import type { HistoryPage } from "../chat/chat-stream-model";
import type { AgentStatus } from "../protocol/tree";
import type { AgentStatusResponse } from "./agents";
import type { AgentBackupSettings, BackupInfo } from "./backups";
import type { FileReadResponse, FileTreeEntry } from "./files";
import type { GatewayEndpointInfo, GatewaySettings } from "./gateway";
import type { HostMount } from "./mounts";
import type {
  AttachmentCompleted,
  AttachmentCreated,
  AttachmentStatus,
  ChatImportAck,
  ChatPostAck,
  RoomOpened,
  RoomsResponse,
} from "./rooms";

type DeepReadonly<T> = T extends (infer U)[]
  ? readonly DeepReadonly<U>[]
  : T extends object
    ? { readonly [K in keyof T]: DeepReadonly<T[K]> }
    : T;

// Cross-language API contract: the fixtures are generated by vestad's Rust test
// (serve.rs::api_contract_fixtures_up_to_date) using the production serialization code.
// Each `satisfies` below is a COMPILE-TIME check (fails `npm run check` / vitest) that
// vestad's wire format is accepted by the TypeScript type the clients use for it.
//
// Direction matters: vestad may send extra fields (TS ignores them), and TS unions may
// have extra members (like the client-side "restarting" status), but every field a TS
// type requires must come over the wire with a compatible shape.
describe("vestad API contract", () => {
  it("every AgentStatus value vestad emits is known to the clients", () => {
    const statuses =
      vestadApiFixtures.agent_statuses satisfies readonly AgentStatus[];
    expect(statuses).toContain("alive");
    expect(statuses).toContain("not_authenticated");
    expect(statuses).toContain("unprovisioned");
  });

  it("the agent status body satisfies AgentStatusResponse", () => {
    const status =
      vestadApiFixtures.agent_status_json satisfies DeepReadonly<AgentStatusResponse>;
    expect(status.booting).toBe(false);
  });

  it("backup listings satisfy BackupInfo for every backup type", () => {
    const backups =
      vestadApiFixtures.backups satisfies readonly DeepReadonly<BackupInfo>[];
    expect(backups.map((backup) => backup.backup_type)).toEqual([
      "manual",
      "periodic",
      "pre_update",
      "pre_restore",
    ]);
  });

  it("per-agent backup settings satisfy AgentBackupSettings", () => {
    const settings =
      vestadApiFixtures.agent_backup_settings satisfies DeepReadonly<AgentBackupSettings>;
    expect(settings.has_override).toBe(false);
  });

  it("tree entries and file reads satisfy the file types", () => {
    const entry = vestadApiFixtures.tree_entry satisfies FileTreeEntry;
    expect(entry.is_dir).toBe(false);
    const read =
      vestadApiFixtures.file_read satisfies DeepReadonly<FileReadResponse>;
    expect(read.encoding).toBe("utf-8");
  });

  it("gateway info and settings satisfy their endpoint types", () => {
    const info =
      vestadApiFixtures.gateway_info satisfies DeepReadonly<GatewayEndpointInfo>;
    expect(info.lan.exposed).toBe(true);
    const settings =
      vestadApiFixtures.gateway_settings satisfies DeepReadonly<GatewaySettings>;
    expect(settings.auto_update).toBe(true);
  });

  it("mounts, the mounts update, the rename, and the folder suggestions satisfy their shapes", () => {
    const mounts = vestadApiFixtures.mounts satisfies DeepReadonly<{
      mounts: HostMount[];
    }>;
    expect(mounts.mounts[0].writable).toBe(false);
    const updated = vestadApiFixtures.mounts_updated satisfies DeepReadonly<{
      mounts: HostMount[];
      restart_required: boolean;
    }>;
    expect(updated.restart_required).toBe(true);
    const renamed = vestadApiFixtures.renamed satisfies { name: string };
    expect(renamed.name).toBe("sample-agent-2");
    const folders = vestadApiFixtures.host_folders satisfies DeepReadonly<{
      folders: string[];
    }>;
    expect(folders.folders).toHaveLength(1);
  });

  it("the chat node's room, history, and intake bodies satisfy their shapes", () => {
    const rooms = vestadApiFixtures.rooms satisfies DeepReadonly<RoomsResponse>;
    expect(rooms.rooms.map((room) => room.id)).toEqual([
      "dm:sample-agent",
      "grp-0011223344556677",
    ]);
    const opened =
      vestadApiFixtures.room_opened satisfies DeepReadonly<RoomOpened>;
    expect(opened.room.name).toBeNull();
    const history =
      vestadApiFixtures.chat_history satisfies DeepReadonly<HistoryPage>;
    expect(history.cursor).toBe(1);
    expect(history.events.map((event) => event.type)).toEqual(["user", "chat"]);
    const post =
      vestadApiFixtures.chat_post satisfies DeepReadonly<ChatPostAck>;
    expect(post.id).toBe(2);
    const imported =
      vestadApiFixtures.chat_import satisfies DeepReadonly<ChatImportAck>;
    expect(imported.skipped).toBe(1);
  });

  it("the attachment acks satisfy their shapes and history carries the metadata", () => {
    const created =
      vestadApiFixtures.attachment_created satisfies DeepReadonly<AttachmentCreated>;
    expect(created.id).toBe("0f1e2d3c4b5a69788796a5b4c3d2e1f0");
    const status =
      vestadApiFixtures.attachment_status satisfies DeepReadonly<AttachmentStatus>;
    expect(status.received).toBe(status.size);
    expect(status.finalized).toBe(true);
    const completed =
      vestadApiFixtures.attachment_completed satisfies DeepReadonly<AttachmentCompleted>;
    expect(completed.attachment.mime).toBe("image/png");
    expect(completed.attachment.width).toBe(640);
    const history =
      vestadApiFixtures.chat_history satisfies DeepReadonly<HistoryPage>;
    const [, reply] = history.events;
    expect(reply.attachments).toEqual([completed.attachment]);
  });
});
