import { describe, expect, it } from "vitest";

import type { BackupInfo } from "@/api/agents";
import type { AuthStartResult } from "@/api/auth";
import type { FileTreeEntry } from "@/api/files";
import type {
  AgentActivityState,
  AgentInfo,
  AgentStatus,
  GatewayVersionInfo,
  VestaEvent,
} from "./types";
import { streamEventFixtures } from "./stream-event-fixtures";
import { vestadApiFixtures } from "./vestad-api-fixtures";

// Cross-language API contract: the fixtures are generated by vestad's Rust test
// (serve.rs::api_contract_fixtures_up_to_date) using the production serialization code.
// Each `satisfies` below is a COMPILE-TIME check (fails `npm run check` / vitest) that
// vestad's wire format is accepted by the TypeScript type the web app uses for it.
//
// Direction matters: vestad may send extra fields (TS ignores them), and TS unions may
// have extra members (like the client-side "restarting" status), but every field a TS
// type requires must come over the wire with a compatible shape.

describe("vestad API contract", () => {
  it("every AgentStatus value vestad emits is known to the web app", () => {
    const statuses =
      vestadApiFixtures.agent_statuses satisfies readonly AgentStatus[];
    expect(statuses).toContain("alive");
    expect(statuses).toContain("not_authenticated");
    expect(statuses).toContain("unprovisioned");
  });

  it("control WS agents message rows satisfy AgentInfo", () => {
    const message = vestadApiFixtures.agents_ws_message;
    expect(message.type).toBe("agents");
    const agents = message.agents satisfies readonly AgentInfo[];
    expect(agents.length).toBeGreaterThan(0);
    expect(agents[0].services.dashboard.port).toBe(8080);
    expect(agents[0].services.dashboard.rev).toBe(3);
  });

  it("backup listings satisfy BackupInfo for every backup type", () => {
    const backups = vestadApiFixtures.backups satisfies readonly BackupInfo[];
    expect(backups.map((backup) => backup.backup_type)).toEqual([
      "manual",
      "daily",
      "weekly",
      "monthly",
      "pre_restore",
    ]);
  });

  it("auth flow response satisfies AuthStartResult", () => {
    const auth = vestadApiFixtures.auth_start satisfies AuthStartResult;
    expect(auth.auth_url).toContain("https://");
    expect(auth.session_id).toBeTruthy();
  });

  it("tree entries satisfy FileTreeEntry", () => {
    const entry = vestadApiFixtures.tree_entry satisfies FileTreeEntry;
    expect(entry.is_dir).toBe(false);
  });

  it("version response satisfies GatewayVersionInfo", () => {
    const version = vestadApiFixtures.version satisfies GatewayVersionInfo;
    expect(version.api_compat).toBe("0.2");
  });
});

// Cross-language stream contract: stream-event-fixtures.ts is generated by the agent's
// stream contract test (REGEN_STREAM_FIXTURES=1 uv run pytest tests/test_contract.py) from
// the StreamEvent/HistoryEvent TypedDicts in agent/core/events.py. The `satisfies` checks below
// are COMPILE-TIME assertions that every field name and field type the agent emits is accepted by
// the web's VestaEvent union, so a contract drift on either side fails `npm run check` / vitest.

describe("agent stream contract", () => {
  it("every stream event the agent emits satisfies VestaEvent", () => {
    const events =
      streamEventFixtures.stream_events satisfies readonly VestaEvent[];
    expect(events.map((event) => event.type)).toEqual([
      "status",
      "user",
      "assistant",
      "thinking",
      "chat",
      "tool_start",
      "tool_end",
      "error",
      "notification",
      "subagent_start",
      "subagent_stop",
    ]);
  });

  it("the history event the agent emits satisfies the history VestaEvent member", () => {
    // VestaEvent's history member nests a mutable VestaEvent[]; the `as const` fixture is deeply
    // readonly, so check the wrapper against a readonly-array history shape and the nested events
    // against `readonly VestaEvent[]`. Both `satisfies` are field-name/field-type compile-time checks.
    const history = streamEventFixtures.history_event satisfies {
      type: "history";
      ts?: string;
      events: readonly VestaEvent[];
      state: AgentActivityState;
      cursor: number | null;
    };
    const nested = history.events satisfies readonly VestaEvent[];
    expect(history.type).toBe("history");
    expect(nested.length).toBeGreaterThan(0);
    expect(history.cursor).toBe(42);
  });
});
