import { describe, expect, it } from "vitest";

import type { AgentStatus } from "@vesta/core";
import type { BackupInfo } from "@/api/agents";
import type { OAuthStartResult } from "@/api/providers/claude";
import type { FileTreeEntry } from "@/api/files";
import { vestadApiFixtures } from "./vestad-api-fixtures";

// Cross-language API contract: the fixtures are generated by vestad's Rust test
// (serve.rs::api_contract_fixtures_up_to_date) using the production serialization code.
// Each `satisfies` below is a COMPILE-TIME check (fails `npm run check` / vitest) that
// vestad's wire format is accepted by the TypeScript type the web app uses for it.
//
// Direction matters: vestad may send extra fields (TS ignores them), and TS unions may
// have extra members (like the client-side "restarting" status), but every field a TS
// type requires must come over the wire with a compatible shape.

describe("vestad API contract", () => {
  it("every AgentStatus value vestad emits is known to the web app", () => {
    const statuses =
      vestadApiFixtures.agent_statuses satisfies readonly AgentStatus[];
    expect(statuses).toContain("alive");
    expect(statuses).toContain("not_authenticated");
    expect(statuses).toContain("unprovisioned");
  });

  it("backup listings satisfy BackupInfo for every backup type", () => {
    const backups = vestadApiFixtures.backups satisfies readonly BackupInfo[];
    expect(backups.map((backup) => backup.backup_type)).toEqual([
      "manual",
      "daily",
      "weekly",
      "monthly",
      "pre_restore",
    ]);
  });

  it("auth flow response satisfies OAuthStartResult", () => {
    const auth = vestadApiFixtures.auth_start satisfies OAuthStartResult;
    expect(auth.auth_url).toContain("https://");
    expect(auth.session_id).toBeTruthy();
  });

  it("tree entries satisfy FileTreeEntry", () => {
    const entry = vestadApiFixtures.tree_entry satisfies FileTreeEntry;
    expect(entry.is_dir).toBe(false);
  });
});
