// AUTO-GENERATED by the agent's stream contract test. Do not edit by hand.
// Regenerate: cd agent && REGEN_STREAM_FIXTURES=1 uv run pytest tests/test_contract.py
// Checked by apps/web/src/lib/api-contract.test.ts against the web's VestaEvent type.
export const streamEventFixtures = {
  "stream_events": [
    {
      "type": "status",
      "ts": "2026-01-01T00:00:00Z",
      "state": "thinking"
    },
    {
      "type": "user",
      "ts": "2026-01-01T00:00:00Z",
      "text": "hello",
      "input_method": "typed"
    },
    {
      "type": "assistant",
      "ts": "2026-01-01T00:00:00Z",
      "text": "hi"
    },
    {
      "type": "thinking",
      "ts": "2026-01-01T00:00:00Z",
      "text": "hmm",
      "signature": "sig"
    },
    {
      "type": "chat",
      "ts": "2026-01-01T00:00:00Z",
      "text": "yo"
    },
    {
      "type": "tool_start",
      "ts": "2026-01-01T00:00:00Z",
      "tool": "Bash",
      "input": "ls",
      "subagent": false
    },
    {
      "type": "tool_end",
      "ts": "2026-01-01T00:00:00Z",
      "tool": "Bash",
      "subagent": false
    },
    {
      "type": "error",
      "ts": "2026-01-01T00:00:00Z",
      "text": "oops"
    },
    {
      "type": "notification",
      "ts": "2026-01-01T00:00:00Z",
      "source": "email",
      "summary": "new mail"
    },
    {
      "type": "notification_cleared",
      "ts": "2026-01-01T00:00:00Z",
      "notif_id": "email-123"
    },
    {
      "type": "subagent_start",
      "ts": "2026-01-01T00:00:00Z",
      "agent_id": "abc",
      "agent_type": "browser"
    },
    {
      "type": "subagent_stop",
      "ts": "2026-01-01T00:00:00Z",
      "agent_id": "abc",
      "agent_type": "browser"
    }
  ],
  "snapshot_event": {
    "type": "snapshot",
    "state": "idle",
    "chat": {
      "events": [
        {
          "type": "status",
          "ts": "2026-01-01T00:00:00Z",
          "state": "idle"
        },
        {
          "type": "assistant",
          "ts": "2026-01-01T00:00:00Z",
          "text": "hi"
        }
      ],
      "cursor": 42
    },
    "notifications": {
      "pending": [
        "email-123"
      ]
    }
  }
} as const;
