name: Deploy Pages

on:
  push:
    branches: [master]
  pull_request:
  release:
    types: [created]

permissions:
  contents: read
  pull-requests: write
  deployments: write

concurrency:
  group: deploy-pages-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy to Cloudflare Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Build
        run: cd app && yarn install && yarn build

      - name: Deploy to Cloudflare Pages
        uses: andykenward/github-actions-cloudflare-pages@v3.3.2
        with:
          cloudflare-api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          cloudflare-account-id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          cloudflare-project-name: vesta
          directory: app/dist
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-environment: ${{ (github.event_name == 'pull_request' && 'preview') || 'production' }}
